


server:
  port: 8081

spring:
  application:
    name: api-gateway

cloud:
  gateway:
    routes:
      - id: articles_feed_service
        uri: http://localhost:8083
        predicates:
          - Path=/articles/**
      - id: blogs_feed_service
        uri: http://localhost:8082
        predicates:
          - Path=/blogs/**
