apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-feed-service
  labels:
    app: article-feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-feed-service
  template:
    metadata:
      labels:
        app: article-feed-service
    spec:
      containers:
        - name: article-feed-service
          image: basmafj/articles_feed_service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
