spring:
  application:
    name: blogs_feed_service
  main:
    web-application-type: REACTIVE
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

