name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/apigateway:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/discovery-service:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/login_service:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/articles_feed_service:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/blog_cr_service:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/blogs_feed_service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.MINIKUBE_KUBECONFIG }}
        run: |
          echo "$KUBECONFIG" | base64 --decode > $HOME/.kube/config
          kubectl apply -f k8s/
